CFLAGS=-std=c99 -Wall -Wextra -pedantic -g3 -O0
CXXFLAGS=-std=c++0x -Wsystem-headers -Wall -Wextra -pedantic -Wcast-qual -Wctor-dtor-privacy -Wnon-virtual-dtor -Weffc++ -Wold-style-cast -Woverloaded-virtual -Wsign-promo -g3 -O0
